shc/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('vax.urls')),
    url(r'^admin/', admin.site.urls),
]

vax/urls.py
from django.conf.urls import url
from django.contrib import admin
from . import views

urlpatterns = [
    url(r'^$', views.index, name = 'home'),
    url(r'^about/$', views.about, name = 'about'),
    #Child's
    url(r'^child/$', views.ChildList.as_view() , name = 'child_list'),
    url(r'^child/(?P<pk>\d+)/$', views.ChildDetail.as_view(), name = 'child_show'),
    url(r'^child/add$', views.ChildCreate.as_view(), name = 'child_add'),
    url(r'^child/(?P<pk>\d+)/edit/$', views.ChildUpdate.as_view(), name = 'child_update'),
    url(r'^child/(?P<pk>\d+)/delete$', views.ChildDelete.as_view(), name = 'child_delete'),
    #Mother
    url(r'^mother/$', views.MotherList.as_view() , name = 'mother_list'),
    url(r'^mother/(?P<pk>\d+)/$', views.MotherDetail.as_view(), name = 'mother_show'),
    url(r'^mother/add$', views.MotherCreate.as_view(), name = 'mother_add'),
    url(r'^mother/(?P<pk>\d+)/edit/$', views.MotherUpdate.as_view(), name = 'mother_update'),
    url(r'^mother/(?P<pk>\d+)/delete$', views.MotherDelete.as_view(), name = 'mother_delete'),
]

vax/models.py
from django.db import models
from django.contrib import admin


# Create your models here.

class Vaccine(models.Model):
    name = models.CharField(max_length=10)
    description = models.TextField()
    month = models.IntegerField(default=0)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class VaccineAdmin(admin.ModelAdmin):
    list_display = ('name','month', 'timestamp', 'updated')




class Mother(models.Model):
    first_name = models.CharField(max_length=50, blank=False, null=False)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    national_id = models.CharField(max_length=11, blank=False, null=False)
    mobile = models.CharField(max_length=12, blank=False, null=False)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def fullname(self):
        return self.first_name + ' ' + self.middle_name + ' ' + self.last_name

    def __str__(self):
        return self.fullname

    def get_absolute_url(self):
        return reverse('mother_show', kwargs={'pk': self.pk})

class MotherAdmin(admin.ModelAdmin):
    list_display = ('fullname','national_id', 'mobile')




class Child(models.Model):
    MALE = 'M'
    FEMALE = 'F'
    GENDER = (
        (MALE, 'Male'),
        (FEMALE, 'Female')
    )

    ACTIVE = 'AC'
    DECEASED = 'DC'
    DISABLED = 'DI'
    STATUS = (
        (ACTIVE,'Active'),
        (DECEASED, 'Deceased'),
        (DISABLED, 'Disabled')
    )
    first_name = models.CharField(max_length=50, blank=False, null=False)
    middle_name = models.CharField(max_length=50, blank=True, null=True)
    last_name = models.CharField(max_length=50, blank=False, null=False)
    national_id = models.CharField(max_length=11, blank=False, null=False, unique=True)
    MRN = models.CharField(max_length=20, blank=True, null=True, unique=True )
    file_no = models.CharField(max_length=11, blank=True, null=True)
    nationality = models.CharField(max_length=20, blank=False, null=False)
    gender = models.CharField(max_length =2, choices = GENDER, default = MALE)
    birth_date = models.DateField()
    status = models.CharField(max_length=2, blank=True, null=True, choices= STATUS)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    mother = models.ForeignKey('Mother', on_delete=models.CASCADE)

    editable_fields = ['first_name', 'middle_name', 'last_name', 'national_id', 'MRN',
                        'file_no', 'nationality', 'gender', 'birth_date', 'status', 'mother']
    
    def my_fields(self):
        return [(field.verbose_name, field.value_to_string(self)) for field in self._meta.fields]

    def fullname(self):
        return self.first_name + ' ' + self.middle_name + ' ' + self.last_name

    def __str__(self):
        return self.fullname

    def get_absolute_url(self):
        return reverse('child_show', kwargs={'pk': self.pk})

class ChildAdmin(admin.ModelAdmin):
    list_display = ('fullname', 'national_id', 'nationality', 'birth_date')




class Appointment(models.Model):
    VACCINATION = 'V'
    FOLLOWUP = 'F'
    CHECKUP = 'C'
    APP_TYPE = (
        (VACCINATION, 'Vaccination'),
        (FOLLOWUP, 'Follow Up'),
        (CHECKUP, 'Check Up')
    )

    PLANNED = 'P'
    POSTPONED = 'S'
    CANCELLED = 'C'
    ATTENDED = 'A'
    APP_STATUS = (
        (PLANNED, 'Planned'),
        (POSTPONED, 'Postponed'),
        (CANCELLED, 'Cancelled'),
        (ATTENDED, 'Attended')
    )
    ap_date = models.DateTimeField()
    ap_type = models.CharField(max_length=2, blank=True, null=True, choices= APP_TYPE, default= VACCINATION)
    ap_status = models.CharField(max_length=2, blank=True, null=True, choices= APP_STATUS, default= PLANNED)
    ap_report = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    child = models.ForeignKey('Child', on_delete=models.CASCADE)
    vaccine = models.ForeignKey('Vaccine', on_delete=models.CASCADE, blank=True, null=True )

    def __str__(self):
        return self.child.fullname

class AppointmentAdmin(admin.ModelAdmin):
    list_display = ('ap_date', 'child', 'ap_type','ap_status','timestamp','updated')




class AppointmentAdmin(admin.ModelAdmin):
    list_display = ('ap_date', 'child', 'ap_type', 'ap_status', 'updated' )






   

vax/forms.py
from django import forms
from django.contrib.admin import widgets
from html5.forms.widgets import DateInput

from .models import (
    Vaccine, Mother, Child, Appointment
)

class ChildForm(forms.ModelForm):
    class Meta:
        model = Child
        fields = [
            'first_name', 'middle_name', 'last_name',  'national_id',
            'MRN', 'file_no', 'nationality', 'gender', 'birth_date',
            'status', 'mother',
        ]
        widgets = {
            'birth_date' : DateInput
        }

class MotherForm(forms.ModelForm):
    class Meta:
        model = Mother
        fields = [
             'first_name', 'middle_name', 'last_name',  'national_id',
            'mobile'
        ]
       

vax/views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from html5.forms.widgets import DateInput

from .models import (
    Vaccine, Mother, Child, Appointment
)
from .forms import ChildForm, MotherForm
# Create your views here.
def index(request):
    return render(request, 'vax/index.html',  {})

#Child============================================
class ChildList(ListView):
    model = Child
    context_object_name = 'children'
    template_name='child/list.html'

class ChildDetail(DetailView):
    model = Child
    template_name='child/show.html'

class ChildCreate(CreateView):
    form_class = ChildForm
    model = Child
    template_name='child/child_form.html'

class ChildUpdate(UpdateView):
    model = Child
    form_class = ChildForm
    template_name='child/child_form.html'
    
class ChildDelete(DeleteView):
    model = Child
    success_url = reverse_lazy('child_list')
#End Child==========================================

#Mother=============================================
class MotherList(ListView):
    model = Mother
    context_object_name = 'mothers'
    template_name='mother/list.html'

class MotherDetail(DetailView):
    model = Mother
    template_name='Mother/show.html'

class MotherCreate(CreateView):
    form_class = MotherForm
    model = Mother
    template_name='mother/mother_form.html'

class MotherUpdate(UpdateView):
    model = Mother
    form_class = MotherForm
    template_name='mother/mother_form.html'
    
class MotherDelete(DeleteView):
    model = Mother
    success_url = reverse_lazy('Mother_list')

#End Mother=========================================

def about(request):
    return render(request, 'vax/about.html', {})



#if request.user.is_authenticated():
#   do something

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Starter Template for Bootstrap</title>

   

   <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->


  </head>

  <body>

      
       <div class="container">

      <!-- Static navbar -->
      <nav class="navbar navbar-inverse">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">{{app}}</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
             
            <ul class="nav navbar-nav">
              <li class="{% if request.path == '/' %} active {% endif %}"><a href="{% url 'home' %}">Home</a></li>
              <li class="{% if request.path == '/about/' %} active {% endif %}"><a href="{% url 'about' %}">About</a></li>
              

              <li class="dropdown {% if 'child' in request.path  %} active {% endif %}" >
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Children <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li class="{% if request.path == '/child/' %} active {% endif %}"><a href="{% url 'child_list' %}">List</a></li>
                  <li class="{% if request.path == '/child/add' %} active {% endif %}"><a href="{% url 'child_add' %}">Add</a></li>
                  <li><a href="#">Reports</a></li>
                </ul>
              </li>

              <li class="dropdown {% if 'mother' in request.path  %} active {% endif %}" >
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Mothers <span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li class="{% if request.path == '/mother/' %} active {% endif %}"><a href="{% url 'mother_list' %}">List</a></li>
                  <li class="{% if request.path == '/mother/add' %} active {% endif %}"><a href="{% url 'mother_add' %}">Add</a></li>
                  <li><a href="#">Reports</a></li>
                </ul>
              </li>

              
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="../navbar-static-top/">Static top</a></li>
              <li><a href="../navbar-fixed-top/">Fixed top</a></li>
              <li class="active"><a href="./admin">Admin <span class="sr-only">(current)</span></a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div><!--/.container-fluid -->
      </nav>

      <!-- Main component for a primary marketing message or call to action -->
      

      {% block content %}
      
      {% endblock content %}

    </div> <!-- /container -->


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
   <!-- Include all compiled plugins (below), or include individual files as needed -->
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>

vax/templates/appointment/appointment_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 col-md-offset-3">
    

<form action="" method="POST" role="form" > {% csrf_token %}
    <legend>Add a Child</legend>
   
    <div class="form-group">
       {{ form|crispy }}
    </div>
    
    <button type="submit" class="btn btn-primary">{% if 'add' in request.path %}Add a Child {% else %} Update {% endif%} </button>
</form>
</div>



{% endblock content %}

vax/templates/appointment/list.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to VAX App</h1>
    </div>

    
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>ID</th>
          <th>Birth Date</th>
          <th>Mother</th>
          <th>Gender</th>
          <th>Status</th>
          <th>File No</th>
          <th>MRN</th>
          <th>Updated</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
       
          {% for child in children %}
          <tr>
          <td><a href="{% url 'child_show' child.id %}">{{ child.fullname }}</a></td>
          <td>{{ child.national_id }}</td>
          <td>{{ child.birth_date }}</td>
          <td>{{ child.mother }}</td>
          <td>{{ child.get_gender_display }}</td>
          <td>{{ child.get_status_display }}</td>
          <td>{{ child.file_no }}</td>
          <td>{{ child.MRN }}</td>
          <td>{{ child.updated }}</td>
          <td align="center" > <a href="{% url 'child_edit' child.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="false"></span></a></td>
        </tr>
          {% endfor %}
       
        
      </tbody>
    </table>
    
{% endblock content %}

vax/templates/appointment/show.html
{% extends "base.html" %}

{% block content %}
   
   <div class="jumbotron">
        <h1>{{ child.fullname }}</h1>
    </div>
<ul class="list-group"> 
          <li class="list-group-item"><strong>National ID:</strong><t/> {{ child.national_id }}</li>
          <li class="list-group-item"><strong>Birth Date:</strong><t/> {{ child.birth_date }}</li>
          <li class="list-group-item"><strong>Mother:</strong><t/> {{ child.mother }}</li>
          <li class="list-group-item"><strong>Gender:</strong><t/> {{ child.get_gender_display }}</li>
          <li class="list-group-item"><strong>Status:</strong><t/> {{ child.get_status_display }}</li>
          <li class="list-group-item"><strong>File Number:</strong><t/> {{ child.file_no }}</li>
          <li class="list-group-item"><strong>MRN:</strong><t/> {{ child.MRN }}</li>
          <li class="list-group-item"><strong>Updated:</strong><t/> {{ child.updated }}</li>
</ul>   

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        {% for name, value in child.my_fields %}
        <tr>
            <td>{{ name }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

vax/templates/child/child_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 col-md-offset-3">
    

<form action="" method="POST" role="form" > {% csrf_token %}
    <legend>Add a Child</legend>
   
    <div class="form-group">
       {{ form|crispy }}
    </div>
    
    <button type="submit" class="btn btn-primary">{% if 'add' in request.path %}Add a Child {% else %} Update {% endif%} </button>
</form>
</div>



{% endblock content %}

vax/templates/child/list.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to VAX App</h1>
    </div>

    
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>ID</th>
          <th>Birth Date</th>
          <th>Mother</th>
          <th>Gender</th>
          <th>Status</th>
          <th>File No</th>
          <th>MRN</th>
          <th>Updated</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
       
          {% for child in children %}
          <tr>
          <td><a href="{% url 'child_show' child.id %}">{{ child.fullname }}</a></td>
          <td>{{ child.national_id }}</td>
          <td>{{ child.birth_date }}</td>
          <td><a href="{% url 'mother_show' child.mother.id %}">{{ child.mother }}</a></td>
          <td>{{ child.get_gender_display }}</td>
          <td>{{ child.get_status_display }}</td>
          <td>{{ child.file_no }}</td>
          <td>{{ child.MRN }}</td>
          <td>{{ child.updated }}</td>
          <td align="center" > 
            <button type="submit" class="btn btn-default">
              <a href="{% url 'child_update' child.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="false"></span></a>
            </button>
            <form action="{% url 'child_delete' child.pk %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-default"><span type="submit" class="glyphicon glyphicon-trash"></span></button>
            </form>
          
          </td>
        </tr>
          {% endfor %}
       
        
      </tbody>
    </table>
    
{% endblock content %}

vax/templates/mother/list.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Mothers</h1>
    </div>

    
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>National ID</th>
          <th>Mobile</th>
          <th>Updated</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
       
          {% for mother in mothers %}
          <tr>
          <td><a href="{% url 'mother_show' mother.id %}">{{ mother.fullname }}</a></td>
          <td>{{ mother.national_id }}</td>
          <td>{{ mother.mobile }}</td>
          <td>{{ mother.updated }}</td>
          <td align="center" >
            <button type="submit" class="btn btn-default">
             <a href="{% url 'mother_update' mother.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="false"></span></a>
            </button>
            <form action="{% url 'mother_delete' mother.pk %}" method="post">
              {% csrf_token %}
              <button type="submit" class="btn btn-default"><span type="submit" class="glyphicon glyphicon-trash"></span></button>
            </form>
          </td>
        </tr>
          {% endfor %}
       
        
      </tbody>
    </table>
    
{% endblock content %}

vax/templates/mother/mother_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 col-md-offset-3">
    

<form action="" method="POST" role="form" > {% csrf_token %}
    <legend>Add a Mother</legend>
   
    <div class="form-group">
       {{ form|crispy }}
    </div>
    
    <button type="submit" class="btn btn-primary">{% if 'add' in request.path %}Add a Mother {% else %} Update {% endif%} </button>
</form>
</div>



{% endblock content %}

vax/templates/mother/show.html
{% extends "base.html" %}

{% block content %}
   
   <div class="jumbotron">
        <h1>{{ mother.fullname }}</h1>
    </div>
   

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
       
        <tr>
            <td><strong>First Name</strong></td>
            <td>{{ mother.first_name }}</td>
        </tr>
         <tr>
            <td><strong>Middle Name</strong></td>
            <td>{{ mother.middle_name }}</td>
        </tr>
         <tr>
            <td><strong>Last Name</strong></td>
            <td>{{ mother.last_name }}</td>
        </tr>
         <tr>
            <td><strong>National ID</strong></td>
            <td>{{ mother.national_id }}</td>
        </tr>
         <tr>
            <td><strong>Mobile #</strong></td>
            <td>{{ mother.mobile }}</td>
        </tr>
       
    </tbody>
</table>


{% endblock content %}

vax/templates/vaccine/list.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to VAX App</h1>
    </div>

    
    <table class="table table-bordered table-hover">
      <thead>
        <tr>
          <th>Name</th>
          <th>ID</th>
          <th>Birth Date</th>
          <th>Mother</th>
          <th>Gender</th>
          <th>Status</th>
          <th>File No</th>
          <th>MRN</th>
          <th>Updated</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
       
          {% for child in children %}
          <tr>
          <td><a href="{% url 'child_show' child.id %}">{{ child.fullname }}</a></td>
          <td>{{ child.national_id }}</td>
          <td>{{ child.birth_date }}</td>
          <td>{{ child.mother }}</td>
          <td>{{ child.get_gender_display }}</td>
          <td>{{ child.get_status_display }}</td>
          <td>{{ child.file_no }}</td>
          <td>{{ child.MRN }}</td>
          <td>{{ child.updated }}</td>
          <td align="center" > <a href="{% url 'child_edit' child.id %}"><span class="glyphicon glyphicon-pencil" aria-hidden="false"></span></a></td>
        </tr>
          {% endfor %}
       
        
      </tbody>
    </table>
    
{% endblock content %}

vax/templates/vaccine/show.html
{% extends "base.html" %}

{% block content %}
   
   <div class="jumbotron">
        <h1>{{ child.fullname }}</h1>
    </div>
<ul class="list-group"> 
          <li class="list-group-item"><strong>National ID:</strong><t/> {{ child.national_id }}</li>
          <li class="list-group-item"><strong>Birth Date:</strong><t/> {{ child.birth_date }}</li>
          <li class="list-group-item"><strong>Mother:</strong><t/> {{ child.mother }}</li>
          <li class="list-group-item"><strong>Gender:</strong><t/> {{ child.get_gender_display }}</li>
          <li class="list-group-item"><strong>Status:</strong><t/> {{ child.get_status_display }}</li>
          <li class="list-group-item"><strong>File Number:</strong><t/> {{ child.file_no }}</li>
          <li class="list-group-item"><strong>MRN:</strong><t/> {{ child.MRN }}</li>
          <li class="list-group-item"><strong>Updated:</strong><t/> {{ child.updated }}</li>
</ul>   

<table class="table table-bordered table-hover">
    <thead>
        <tr>
            <th>Property</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        {% for name, value in child.my_fields %}
        <tr>
            <td>{{ name }}</td>
            <td>{{ value }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>


{% endblock content %}

vax/templates/vaccine/vaccine_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-6 col-md-offset-3">
    

<form action="" method="POST" role="form" > {% csrf_token %}
    <legend>Add a Child</legend>
   
    <div class="form-group">
       {{ form|crispy }}
    </div>
    
    <button type="submit" class="btn btn-primary">{% if 'add' in request.path %}Add a Child {% else %} Update {% endif%} </button>
</form>
</div>



{% endblock content %}

vax/templates/vax/about.html
{% extends "base.html" %}

{% block content %}
   
   <div class="jumbotron">
        <h1>Abou Us</h1>
    </div>

{% endblock content %}

vax/templates/vax/index.html
{% extends "base.html" %}

{% block content %}
    <div class="jumbotron">
        <h1>Welcome to VAX App</h1>
    </div>

    
    
    
{% endblock content %}